# Generated by Django 4.2.3 on 2023-07-21 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("task_name", models.CharField(max_length=255)),
                ("task_description", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TO DO", "To do"),
                            ("IN PROGRESS", "In progress"),
                            ("COMPLETED", "Completed"),
                        ],
                        db_index=True,
                        default="TO DO",
                        max_length=50,
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 7, 21, 11, 53, 30, 168895)
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 7, 21, 11, 53, 30, 168902)
                    ),
                ),
            ],
        ),
    ]
